// File generated by Antigravity
// Replacement for gitignored firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported for this target.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not supported for this target.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not supported for this target.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported for this target.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzbSzCn1', // User provided
    appId: '123456789000', // User provided
    messagingSenderId: '123456789000', // Using App ID prefix/placeholder
    projectId: 'mockproject-1234', // User provided
    storageBucket: 'mockproject-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzbSzCn1',
    appId: '123456789000',
    messagingSenderId: '123456789000',
    projectId: 'mockproject-1234',
    storageBucket: 'mockproject-1234.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
