// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web, and web is not supported by this application.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase is not supported on ${defaultTargetPlatform.toString().split('.').last} for this configuration.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Konfigurasi Android sudah benar dan diambil dari hasil konfigurasi Anda.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17xOzYduCkA0ysazqUN9PB9nmVSkPHdY',
    appId: '1:930642279279:android:ffa45aea9cf7d6f311069a',
    messagingSenderId: '930642279279',
    projectId: 'pull-up-detection-app',
    storageBucket: 'pull-up-detection-app.firebasestorage.app',
  );
}
